name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1 # https://github.com/actions/checkout/releases
      - uses: asdf-vm/actions/install@v3.0.2 # https://github.com/asdf-vm/actions/releases
      - run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1 # https://github.com/actions/checkout/releases
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.26 # https://hub.docker.com/r/rhysd/actionlint/tags
        with:
          args: -color
