name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
          - ubuntu-22.04
          - macos-12 # x86_64
          - macos-14 # arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3.0.2 # https://github.com/asdf-vm/actions/releases
        with:
          command: tofu --help
